name: "web_app"
mode: "dev"
host: "127.0.0.1"
port: "8888"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: "200"
  max_backups : "1"
  max_age : "30"
mysql:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "root"
  dbname: "web_app"
  charset: "utf8mb4"
  max_open_conns: "200"
  max_idle_conns: "10"
redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  database: "0"
  pool_size : "1000"